version: '3.2'
services:
  notebook:
    image: jupyter
    container_name: notebook
    build: notebook/
    ports:
      - 8888:8888
    volumes:
      - ./storage:/notebook/storage
  client:
    image: client
    container_name: client
    command: python3 main.py
    build: client/
    volumes:
      - ./storage:/client/storage

volumes:
  data:
    external:
      true
    name:
      storage